### PR TITLE
Remove `CStringNode`, use `ConstantNode` with `CStringConstant` instead.

### PR DESCRIPTION
**Pull request by rschatz**
Just some cleanup opportunity I stumbled over while working on the exception stubs. That way, the constant optimizations by the backend and register allocator will also apply to raw c string constants.

This passes all unit tests on AMD64 and SPARC locally. I hope I didn't break AArch64, but since it's only a change to the interface of the backend, not to the implementation, my chances are good ;)

/cc @sanzinger

### CODE REVIEW

**Comment by christhalinger** [comment]
Do you guys have access to an ARMv8 board?

**Comment by dougxc** [comment]
Not where I am.

**Comment by dougxc** [comment]
lgtm

**Comment by zapster** [comment]
@christhalinger no :|

**Comment by tkrodriguez** [comment]
looks good

**Pull request merged**
