### PR TITLE
Rationalize dump levels and change default to 1

### PR DESCRIPTION
**Pull request by tkrodriguez**
I made the levels more explicit and forced the call sites to actively pick one.  Most of the ones using dump stayed at level 2 but I tried to change all debugging and testing ones to 1.  I also added support for symbolic names in the dump specifiers so you can say -G:Dump=:verbose to get level 3.  I also adjusted places where a constant integer was being passed instead of a symbolic name.

cc @dougxc @gilles-duboscq @zapster @thomaswue

### CODE REVIEW

**Comment by zapster** [comment]
I like the change, just a few remarks about the naming. For me it is not really intuitive that that `info` is more verbose than `basic`. Also, for new users of the API it might not be clear that `basic` is the default and that it is supposed to be the least verbose level. Maybe it just me being spoiled by other systems using similar names.

**Comment by dougxc** [comment]
lgtm

**Comment by tkrodriguez** [comment]
I wasn't totally happy with the difference between the names either.  The intent was that basic was the minimum, info was extra stuff, and verbose is stuff you rarely care about.  I'm up for a renaming if you have better suggestions.

**Comment by dougxc** [comment]
The naming doesn't really bother me but `TERSE_LOG_LEVEL` is one suggestion.

**Comment by tkrodriguez** [comment]
I don't feel like that's much of an improvement.  Adopting something stolen from log4j would give us INFO,DEBUG,TRACE with increasing levels of verbosity.   I don't like that much either.  Anyway, if someone wants something different feel free to propose it but I'll leave it alone for now.

**Pull request merged**
