### PR TITLE
Add paper Accelerating iterators in optimizing AST interpreters (OOPSLA14)

### PR DESCRIPTION
**Pull request by thezhangwei**
Hi, I thought I should add my ZipPy paper from OOPSLA14 to the Truffle paper collections.
Thanks,

### CODE REVIEW

**Comment by thezhangwei** [comment]
Hmm I'm not sure if I can go through the OCA thing at the moment..
@dougxc would you mind adding the paper on my behalf? :)

**Comment by dougxc** [comment]
Can do.

**Comment by thezhangwei** [comment]
Thank you Doug!

**Comment by dougxc** [comment]
https://github.com/graalvm/graal-core/commit/6a44fba8e8004fe12934dc31e4f5dbb8dc6b26b3

**Pull request closed without merging**
