### PR TITLE
Investigate travis failure

### PR DESCRIPTION
**Pull request by tkrodriguez**

### CODE REVIEW

**Comment by dougxc** [comment]
@gilles-duboscq saw a Truffle failure today while making Graal work again with JDK 9. I think it may be the same one that @theRealAph reported and that I assume you're trying to reproduce here.

**Comment by tkrodriguez** [comment]
Yes it seems pretty reliable in the gate https://travis-ci.org/graalvm/graal-core/jobs/197749872

**Comment by tkrodriguez** [comment]
I was concerned that indexOf might be implicated but disabling it had no effect.  I'll try backing up a few commits instead.

**Comment by tkrodriguez** [comment]
I'm investigating this over at https://github.com/tkrodriguez/graal-core/pull/1 since the gate automerges against master which defeats the ability to test individual changesets.

**Pull request closed without merging**
